/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Exercicio2;

/**
 *
 * @author Jeff
 */
public class FrameLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrameLogin
     */
    public FrameLogin() {
        initComponents();
        lblTitulo.setBounds(90, 20, 180, 15);
        lblLogin.setBounds(30, 50, 29, 20);
        lblPassword.setBounds(20, 90, 53, 15);
        jTFLogin.setBounds(80, 50, 210, 20);
        jPFPassword.setBounds(80, 90, 210, 20);
        jPanelBotoes.setBounds(30, 120, 280, 60);
        btnOk.setBounds(70,20,47,23);
        btnCancelar.setBounds(150, 20, 75, 23);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        jTFLogin = new javax.swing.JTextField();
        jPFPassword = new javax.swing.JPasswordField();
        jPanelBotoes = new javax.swing.JPanel();
        btnOk = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblTitulo.setBackground(java.awt.Color.red);
        lblTitulo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblTitulo.setForeground(java.awt.Color.red);
        lblTitulo.setText("Título");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(30, 20, 80, 20);

        lblLogin.setText("Insira seu Login!");
        getContentPane().add(lblLogin);
        lblLogin.setBounds(30, 50, 80, 14);

        lblPassword.setText("Insira sua senha");
        getContentPane().add(lblPassword);
        lblPassword.setBounds(30, 90, 90, 14);

        jTFLogin.setText("jTextField1");
        getContentPane().add(jTFLogin);
        jTFLogin.setBounds(120, 50, 150, 20);

        jPFPassword.setText("jPasswordField1");
        getContentPane().add(jPFPassword);
        jPFPassword.setBounds(120, 90, 96, 20);

        jPanelBotoes.setBackground(java.awt.Color.blue);
        jPanelBotoes.setForeground(java.awt.Color.blue);
        jPanelBotoes.setLayout(null);

        btnOk.setText("Ok");
        jPanelBotoes.add(btnOk);
        btnOk.setBounds(70, 20, 47, 23);

        btnCancelar.setText("Sair do Programa");
        btnCancelar.setToolTipText("");
        jPanelBotoes.add(btnCancelar);
        btnCancelar.setBounds(150, 20, 130, 23);

        getContentPane().add(jPanelBotoes);
        jPanelBotoes.setBounds(30, 120, 320, 60);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnOk;
    private javax.swing.JPasswordField jPFPassword;
    private javax.swing.JPanel jPanelBotoes;
    private javax.swing.JTextField jTFLogin;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
